/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Employee {
  departement?: string;
  id?: string;
  name?: string;
  position?: string;
  salary?: number;
  surname?: string;
}
